# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
    args:
    - --assume-in-merge
  - id: check-vcs-permalinks
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-private-key
  # - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  # - id: no-commit-to-branch
  - id: trailing-whitespace
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.4.0
  hooks:
  - id: editorconfig-checker
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.1
  hooks:
  - id: markdownlint
